// Generated by Wrangler by running `wrangler types`

interface Env {
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_API_TOKEN: string;
	CLOUDFLARE_TUNNEL_ID: string;
	CLOUDFLARE_ZONE_ID: string;
	DOMAIN_NAME: string;
}
